"""Validated, thread-safe smart-home simulator used by Hachi's Home mode."""

from __future__ import annotations

import copy
import json
import os
import re
import threading
import time
from collections import deque
from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator


ActionName = Literal[
    "turn_on", "turn_off", "set_temperature", "increase_temperature",
    "decrease_temperature", "lock", "unlock", "play_media", "pause_media",
    "stop_media",
]
TargetName = Literal[
    "living_room_light", "kitchen_light", "living_room_thermostat",
    "front_door_lock", "entertainment",
]


class SmartHomeAction(BaseModel):
    """One allow-listed operation generated by the local model."""

    model_config = ConfigDict(extra="forbid")

    action: ActionName
    target: TargetName
    value: float | None = None
    title: str | None = Field(default=None, max_length=80)

    @model_validator(mode="after")
    def validate_action_target(self):
        lights = {"living_room_light", "kitchen_light"}
        thermostat_actions = {"set_temperature", "increase_temperature", "decrease_temperature"}
        media_actions = {"play_media", "pause_media", "stop_media"}

        if self.target in lights and self.action not in {"turn_on", "turn_off"}:
            raise ValueError("Lights only support turn_on and turn_off.")
        if self.target == "living_room_thermostat" and self.action not in thermostat_actions:
            raise ValueError("The thermostat only supports temperature actions.")
        if self.target == "front_door_lock" and self.action not in {"lock", "unlock"}:
            raise ValueError("The front door only supports lock and unlock.")
        if self.target == "entertainment" and self.action not in media_actions:
            raise ValueError("Entertainment only supports media actions.")
        if self.action in thermostat_actions:
            if self.value is None:
                if self.action in {"increase_temperature", "decrease_temperature"}:
                    self.value = 2.0
                else:
                    self.value = 22.0
            if self.action == "set_temperature":
                if self.value > 30:
                    self.value = 30.0
                elif self.value < 16:
                    self.value = 16.0
            else:
                if self.value <= 0:
                    self.value = 1.0
                elif self.value > 10:
                    self.value = 5.0
        elif self.value is not None:
            raise ValueError("Only temperature actions accept a numeric value.")
        return self


class SmartHomeCommand(BaseModel):
    """Atomic action envelope accepted by the simulator."""

    model_config = ConfigDict(extra="forbid")

    goal: str = Field(default="Update the smart home", max_length=240)
    actions: list[SmartHomeAction] = Field(min_length=1, max_length=6)


_INITIAL_DEVICES = {
    "living_room_light": {"on": False},
    "kitchen_light": {"on": True},
    "living_room_thermostat": {"temperature_c": 20},
    "front_door_lock": {"locked": False},
    "entertainment": {"status": "stopped", "title": ""},
}

_LOCK = threading.RLock()
_DEVICES = copy.deepcopy(_INITIAL_DEVICES)
_REVISION = 0
_UPDATED_AT = datetime.now().astimezone().isoformat(timespec="seconds")
_EVENTS: deque[dict] = deque(maxlen=12)
_LOG_PATH = os.path.join(os.path.dirname(__file__), "assistant_execution.log")


def _now() -> str:
    return datetime.now().astimezone().isoformat(timespec="milliseconds")


def _snapshot_locked() -> dict:
    return {
        "revision": _REVISION,
        "updated_at": _UPDATED_AT,
        "devices": copy.deepcopy(_DEVICES),
        "events": copy.deepcopy(list(_EVENTS)),
    }


def get_smart_home_state() -> dict:
    """Return an isolated copy of the current simulator state."""
    with _LOCK:
        return _snapshot_locked()


def is_smart_home_request(text: str) -> bool:
    """Recognize likely home requests outside the explicit Home dashboard."""
    value = (text or "").lower()
    return bool(re.search(
        r"\b(?:smart\s*home|thermostat|temperature|degrees?|light|lights|bulb|bulbs|lamp|lamps|"
        r"front door|door lock|door|lock|unlock|locked|unlocked|living room|kitchen|"
        r"freez(?:e|ing)|chilly|boiling|hot|cold|warm|cooler|colder|warmer|hotter|"
        r"cool(?:ing)?\s+(?:the\s+room|down|it|the\s+house)|"
        r"warm(?:ing)?\s+(?:the\s+room|up|it|the\s+house)|"
        r"heat(?:\s+up)?|"
        r"too (?:hot|cold|dark|bright)|so (?:hot|cold|warm|dark|bright)|getting (?:dark|cold|hot|warm)|"
        r"turn (?:everything|all|both|all the lights) (?:off|on)|"
        r"(?:turn|switch)\s+(?:off|on)\s+(?:everything|all|both)|"
        r"unlock (?:everything|all|the door)|lock (?:everything|all|the door)|"
        r"make it (?:colder|cooler|warmer|hotter|darker|brighter|cold|cool|warm|hot)|"
        r"secure (?:the )?(?:house|home|door)|movie night|study music|entertainment|tv|television)\b",
        value,
    ))


def infer_smart_home_actions(text: str) -> list[dict]:
    """Fallback rule-based extractor to infer smart-home actions if model fails or truncates."""
    lower = (text or "").lower()
    actions = []

    # Global "everything / all" switches
    if re.search(r"\b(?:turn\s+everything\s+off|turn\s+all\s+off|turn\s+off\s+everything|turn\s+off\s+all|switch\s+off\s+all|kill\s+all\s+lights|turn\s+off\s+all\s+lights)\b", lower):
        actions.append({"action": "turn_off", "target": "living_room_light"})
        actions.append({"action": "turn_off", "target": "kitchen_light"})
        actions.append({"action": "stop_media", "target": "entertainment"})
    elif re.search(r"\b(?:turn\s+everything\s+on|turn\s+all\s+on|turn\s+on\s+everything|turn\s+on\s+all|switch\s+on\s+all|turn\s+on\s+all\s+lights)\b", lower):
        actions.append({"action": "turn_on", "target": "living_room_light"})
        actions.append({"action": "turn_on", "target": "kitchen_light"})

    if re.search(r"\b(?:unlock\s+everything|unlock\s+all|unlock\s+(?:the\s+)?door)\b", lower):
        actions.append({"action": "unlock", "target": "front_door_lock"})
    elif re.search(r"\b(?:lock\s+everything|lock\s+all|lock\s+(?:the\s+)?door|secure\s+the\s+house)\b", lower):
        actions.append({"action": "lock", "target": "front_door_lock"})

    # Specific Living room light
    if "living room" in lower and any(w in lower for w in ("light", "lights", "lamp")):
        if re.search(r"\b(?:turn\s+on|switch\s+on|open|enable)\b.*?\bliving\s+room\b|\bliving\s+room\b.*?\b(?:turn\s+on|switch\s+on|on)\b", lower):
            actions.append({"action": "turn_on", "target": "living_room_light"})
        elif re.search(r"\b(?:turn\s+off|switch\s+off|close|disable|kill)\b.*?\bliving\s+room\b|\bliving\s+room\b.*?\b(?:turn\s+off|switch\s+off|off)\b", lower):
            actions.append({"action": "turn_off", "target": "living_room_light"})

    # Specific Kitchen light
    if "kitchen" in lower and any(w in lower for w in ("light", "lights", "lamp")):
        if re.search(r"\b(?:turn\s+on|switch\s+on|open|enable)\b.*?\bkitchen\b|\bkitchen\b.*?\b(?:turn\s+on|switch\s+on|on)\b", lower):
            actions.append({"action": "turn_on", "target": "kitchen_light"})
        elif re.search(r"\b(?:turn\s+off|switch\s+off|close|disable|kill)\b.*?\bkitchen\b|\bkitchen\b.*?\b(?:turn\s+off|switch\s+off|off)\b", lower):
            actions.append({"action": "turn_off", "target": "kitchen_light"})

    # General lights (e.g. "open the lights", "turn on the lights", "turn off the lights")
    if any(w in lower for w in ("light", "lights", "lamp", "lamps")) and "living room" not in lower and "kitchen" not in lower:
        if re.search(r"\b(?:turn\s+on|switch\s+on|open|enable)\b", lower):
            actions.append({"action": "turn_on", "target": "living_room_light"})
            actions.append({"action": "turn_on", "target": "kitchen_light"})
        elif re.search(r"\b(?:turn\s+off|switch\s+off|close|disable|kill)\b", lower):
            actions.append({"action": "turn_off", "target": "living_room_light"})
            actions.append({"action": "turn_off", "target": "kitchen_light"})

    # Specific Front door lock
    if any(w in lower for w in ("door", "lock", "front door")):
        if re.search(r"\b(?:unlock|open)\b.*?\b(?:door|lock)\b|\b(?:door|lock)\b.*?\b(?:unlock|unlocked)\b", lower):
            actions.append({"action": "unlock", "target": "front_door_lock"})
        elif re.search(r"\b(?:lock|secure|close)\b.*?\b(?:door|front door|house)\b", lower):
            actions.append({"action": "lock", "target": "front_door_lock"})

    # Thermostat
    if any(w in lower for w in ("thermostat", "temperature", "temp", "warm", "warmer", "hot", "hotter", "cold", "colder", "cool", "cooler", "heat", "freezing", "chilly", "boiling")):
        val_match = re.search(r"\b(\d{1,2}(?:\.\d+)?)\s*(?:°|c|degrees|deg|celsius)?\b", lower)
        # Increase temperature (heating up / user is cold)
        if re.search(r"\b(?:increase|raise|turn up|warmer|hotter|warm\s+up|heat\s+up|warm\s+the\s+room|make it warm|make it hot|make it warmer|im cold|i'm cold|so cold|too cold|very cold|freezing|chilly)\b", lower):
            actions.append({"action": "increase_temperature", "target": "living_room_thermostat", "value": 2.0})
        # Decrease temperature (cooling down / user is hot)
        elif re.search(r"\b(?:decrease|lower|turn down|cooler|colder|cool\s+down|cool\s+the\s+room|cool\s+it|make it cool|make it cold|make it colder|make it cooler|im hot|i'm hot|so hot|too hot|very hot|boiling|burning)\b", lower):
            actions.append({"action": "decrease_temperature", "target": "living_room_thermostat", "value": 2.0})
        elif val_match:
            actions.append({"action": "set_temperature", "target": "living_room_thermostat", "value": float(val_match.group(1))})

    # Entertainment / TV
    if any(w in lower for w in ("tv", "television", "entertainment", "movie", "music", "song")):
        if re.search(r"\b(?:turn\s+on|start|play|watch|open)\b.*?\b(?:tv|television|movie|music)\b|\b(?:tv|television)\b.*?\b(?:on|play)\b", lower):
            actions.append({"action": "play_media", "target": "entertainment", "title": "TV"})
        elif re.search(r"\b(?:pause)\b", lower):
            actions.append({"action": "pause_media", "target": "entertainment"})
        elif re.search(r"\b(?:turn\s+off|stop|close)\b.*?\b(?:tv|television|entertainment|music)\b", lower):
            actions.append({"action": "stop_media", "target": "entertainment"})

    # Deduplicate by target
    seen = {}
    for a in actions:
        seen[a["target"]] = a
    return list(seen.values())


def smart_home_prompt_context() -> str:
    """Provide Qwen a small state/action contract rather than the full app internals."""
    state = get_smart_home_state()
    return (
        "\n\nSMART HOME MODE:\n"
        "Interpret the user's real need, including indirect phrases such as 'it is dark' "
        "or 'I am freezing'. For a requested state change, call control_smart_home once "
        "with every required action. For a state question, call get_smart_home_state. "
        "Never claim a device changed unless the tool reports success. Ask one short "
        "clarifying question when the target or desired state is genuinely ambiguous.\n"
        f"CURRENT SMART HOME STATE: {json.dumps(state['devices'], ensure_ascii=False)}"
    )


def _append_execution_log(event: dict) -> None:
    with open(_LOG_PATH, "a", encoding="utf-8") as log_file:
        log_file.write(json.dumps(event, ensure_ascii=False, default=str) + "\n")


def _describe_change(target: str, before: object, after: object) -> str:
    label = target.replace("_", " ")
    return f"{label}: {before} -> {after}"


def record_smart_home_rejection(
    actions: object,
    error: object,
    goal: str = "Update the smart home",
    original_command: str = "",
    engine: str = "qwen",
) -> dict:
    """Record rejected model output without mutating any device state."""
    with _LOCK:
        event = {
            "timestamp": _now(),
            "event": "smart_home_command_rejected",
            "transcript": original_command,
            "goal": goal,
            "engine": engine,
            "proposed_actions": copy.deepcopy(actions),
            "error": str(error),
            "state_before": copy.deepcopy(_DEVICES),
            "state_after": copy.deepcopy(_DEVICES),
            "changes": [],
            "validation_success": False,
            "execution_verified": False,
            "execution_ms": 0,
            "total_ms": 0,
            "revision": _REVISION,
        }
        _EVENTS.appendleft(copy.deepcopy(event))
    _append_execution_log(event)
    return event


def apply_smart_home_actions(
    actions: list[dict],
    goal: str = "Update the smart home",
    original_command: str = "",
    engine: str = "qwen",
    request_started_at: float | None = None,
) -> dict:
    """Validate then atomically apply a model-produced action envelope."""
    command = SmartHomeCommand.model_validate({"goal": goal, "actions": actions})
    execution_started = time.perf_counter()

    global _DEVICES, _REVISION, _UPDATED_AT
    with _LOCK:
        before = copy.deepcopy(_DEVICES)
        working = copy.deepcopy(_DEVICES)

        for item in command.actions:
            if item.target in {"living_room_light", "kitchen_light"}:
                working[item.target]["on"] = item.action == "turn_on"
            elif item.target == "living_room_thermostat":
                current = float(working[item.target]["temperature_c"])
                if item.action == "set_temperature":
                    new_temperature = float(item.value)
                elif item.action == "increase_temperature":
                    new_temperature = current + float(item.value)
                else:
                    new_temperature = current - float(item.value)
                if not 16 <= new_temperature <= 30:
                    raise ValueError("The resulting thermostat value must be between 16 and 30 C.")
                working[item.target]["temperature_c"] = int(new_temperature) if new_temperature.is_integer() else round(new_temperature, 1)
            elif item.target == "front_door_lock":
                working[item.target]["locked"] = item.action == "lock"
            elif item.target == "entertainment":
                if item.action == "play_media":
                    working[item.target]["status"] = "playing"
                    working[item.target]["title"] = (item.title or "Media").strip()
                elif item.action == "pause_media":
                    working[item.target]["status"] = "paused"
                else:
                    working[item.target] = {"status": "stopped", "title": ""}

        changes = []
        for target in working:
            if before[target] != working[target]:
                changes.append({
                    "target": target,
                    "before": before[target],
                    "after": working[target],
                    "summary": _describe_change(target, before[target], working[target]),
                })

        _DEVICES = working
        _REVISION += 1
        _UPDATED_AT = _now()
        execution_ms = round((time.perf_counter() - execution_started) * 1000, 2)
        total_ms = round((time.perf_counter() - request_started_at) * 1000, 2) if request_started_at else execution_ms
        event = {
            "timestamp": _UPDATED_AT,
            "event": "smart_home_command",
            "transcript": original_command,
            "goal": command.goal,
            "engine": engine,
            "validated_actions": [item.model_dump(exclude_none=True) for item in command.actions],
            "state_before": before,
            "state_after": copy.deepcopy(_DEVICES),
            "changes": copy.deepcopy(changes),
            "validation_success": True,
            "execution_verified": all(_DEVICES[item["target"]] == item["after"] for item in changes),
            "execution_ms": execution_ms,
            "total_ms": total_ms,
            "revision": _REVISION,
        }
        _EVENTS.appendleft(copy.deepcopy(event))
        snapshot = _snapshot_locked()

    _append_execution_log(event)
    change_text = "; ".join(change["summary"] for change in changes) or "The requested state was already set."
    return {
        "success": True,
        "message": change_text,
        "goal": command.goal,
        "actions": event["validated_actions"],
        "changes": changes,
        "verification": {"success": event["execution_verified"], "revision": event["revision"]},
        "state": snapshot,
        "timing": {"execution_ms": execution_ms, "total_ms": total_ms},
    }


def reset_smart_home(original_command: str = "Manual dashboard reset") -> dict:
    """Restore a predictable demo state and record the reset."""
    global _DEVICES, _REVISION, _UPDATED_AT
    with _LOCK:
        before = copy.deepcopy(_DEVICES)
        _DEVICES = copy.deepcopy(_INITIAL_DEVICES)
        _REVISION += 1
        _UPDATED_AT = _now()
        event = {
            "timestamp": _UPDATED_AT,
            "event": "smart_home_reset",
            "transcript": original_command,
            "engine": "deterministic",
            "state_before": before,
            "state_after": copy.deepcopy(_DEVICES),
            "validation_success": True,
            "execution_verified": _DEVICES == _INITIAL_DEVICES,
            "execution_ms": 0,
            "total_ms": 0,
            "revision": _REVISION,
        }
        _EVENTS.appendleft(copy.deepcopy(event))
        snapshot = _snapshot_locked()
    _append_execution_log(event)
    return {"success": True, "message": "Smart home reset to the demo state.", "state": snapshot}
