"""Validated, thread-safe smart-home simulator used by Hachi's Home mode."""

from __future__ import annotations

import copy
import json
import os
import re
import threading
import time
from collections import deque
from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator


ActionName = Literal[
    "turn_on", "turn_off", "set_temperature", "increase_temperature",
    "decrease_temperature", "lock", "unlock", "play_media", "pause_media",
    "stop_media",
]
TargetName = Literal[
    "living_room_light", "kitchen_light", "living_room_thermostat",
    "front_door_lock", "entertainment",
]


class SmartHomeAction(BaseModel):
    """One allow-listed operation generated by the local model."""

    model_config = ConfigDict(extra="forbid")

    action: ActionName
    target: TargetName
    value: float | None = None
    title: str | None = Field(default=None, max_length=80)

    @model_validator(mode="after")
    def validate_action_target(self):
        lights = {"living_room_light", "kitchen_light"}
        thermostat_actions = {"set_temperature", "increase_temperature", "decrease_temperature"}
        media_actions = {"play_media", "pause_media", "stop_media"}

        if self.target in lights and self.action not in {"turn_on", "turn_off"}:
            raise ValueError("Lights only support turn_on and turn_off.")
        if self.target == "living_room_thermostat" and self.action not in thermostat_actions:
            raise ValueError("The thermostat only supports temperature actions.")
        if self.target == "front_door_lock" and self.action not in {"lock", "unlock"}:
            raise ValueError("The front door only supports lock and unlock.")
        if self.target == "entertainment" and self.action not in media_actions:
            raise ValueError("Entertainment only supports media actions.")
        if self.action in thermostat_actions:
            if self.value is None:
                raise ValueError("Temperature actions require a numeric value.")
            if self.action == "set_temperature" and not 16 <= self.value <= 30:
                raise ValueError("Thermostat values must be between 16 and 30 C.")
            if self.action != "set_temperature" and not 0 < self.value <= 10:
                raise ValueError("Temperature adjustments must be between 0 and 10 C.")
        elif self.value is not None:
            raise ValueError("Only temperature actions accept a numeric value.")
        return self


class SmartHomeCommand(BaseModel):
    """Atomic action envelope accepted by the simulator."""

    model_config = ConfigDict(extra="forbid")

    goal: str = Field(default="Update the smart home", max_length=240)
    actions: list[SmartHomeAction] = Field(min_length=1, max_length=6)


_INITIAL_DEVICES = {
    "living_room_light": {"on": False},
    "kitchen_light": {"on": True},
    "living_room_thermostat": {"temperature_c": 20},
    "front_door_lock": {"locked": False},
    "entertainment": {"status": "stopped", "title": ""},
}

_LOCK = threading.RLock()
_DEVICES = copy.deepcopy(_INITIAL_DEVICES)
_REVISION = 0
_UPDATED_AT = datetime.now().astimezone().isoformat(timespec="seconds")
_EVENTS: deque[dict] = deque(maxlen=12)
_LOG_PATH = os.path.join(os.path.dirname(__file__), "assistant_execution.log")


def _now() -> str:
    return datetime.now().astimezone().isoformat(timespec="milliseconds")


def _snapshot_locked() -> dict:
    return {
        "revision": _REVISION,
        "updated_at": _UPDATED_AT,
        "devices": copy.deepcopy(_DEVICES),
        "events": copy.deepcopy(list(_EVENTS)),
    }


def get_smart_home_state() -> dict:
    """Return an isolated copy of the current simulator state."""
    with _LOCK:
        return _snapshot_locked()


def is_smart_home_request(text: str) -> bool:
    """Recognize likely home requests outside the explicit Home dashboard."""
    value = (text or "").lower()
    return bool(re.search(
        r"\b(?:smart\s*home|thermostat|temperature|degrees?|light|lights|bulb|"
        r"front door|door lock|lock the door|unlock the door|living room|kitchen|"
        r"freez(?:e|ing)|warmer|cooler|too (?:hot|cold|dark|bright)|getting dark|"
        r"secure (?:the )?(?:house|home|door)|movie night|study music|entertainment)\b",
        value,
    ))


def smart_home_prompt_context() -> str:
    """Provide Qwen a small state/action contract rather than the full app internals."""
    state = get_smart_home_state()
    return (
        "\n\nSMART HOME MODE:\n"
        "Interpret the user's real need, including indirect phrases such as 'it is dark' "
        "or 'I am freezing'. For a requested state change, call control_smart_home once "
        "with every required action. For a state question, call get_smart_home_state. "
        "Never claim a device changed unless the tool reports success. Ask one short "
        "clarifying question when the target or desired state is genuinely ambiguous.\n"
        f"CURRENT SMART HOME STATE: {json.dumps(state['devices'], ensure_ascii=False)}"
    )


def _append_execution_log(event: dict) -> None:
    with open(_LOG_PATH, "a", encoding="utf-8") as log_file:
        log_file.write(json.dumps(event, ensure_ascii=False, default=str) + "\n")


def _describe_change(target: str, before: object, after: object) -> str:
    label = target.replace("_", " ")
    return f"{label}: {before} -> {after}"


def record_smart_home_rejection(
    actions: object,
    error: object,
    goal: str = "Update the smart home",
    original_command: str = "",
    engine: str = "qwen",
) -> dict:
    """Record rejected model output without mutating any device state."""
    with _LOCK:
        event = {
            "timestamp": _now(),
            "event": "smart_home_command_rejected",
            "transcript": original_command,
            "goal": goal,
            "engine": engine,
            "proposed_actions": copy.deepcopy(actions),
            "error": str(error),
            "state_before": copy.deepcopy(_DEVICES),
            "state_after": copy.deepcopy(_DEVICES),
            "changes": [],
            "validation_success": False,
            "execution_verified": False,
            "execution_ms": 0,
            "total_ms": 0,
            "revision": _REVISION,
        }
        _EVENTS.appendleft(copy.deepcopy(event))
    _append_execution_log(event)
    return event


def apply_smart_home_actions(
    actions: list[dict],
    goal: str = "Update the smart home",
    original_command: str = "",
    engine: str = "qwen",
    request_started_at: float | None = None,
) -> dict:
    """Validate then atomically apply a model-produced action envelope."""
    command = SmartHomeCommand.model_validate({"goal": goal, "actions": actions})
    execution_started = time.perf_counter()

    global _DEVICES, _REVISION, _UPDATED_AT
    with _LOCK:
        before = copy.deepcopy(_DEVICES)
        working = copy.deepcopy(_DEVICES)

        for item in command.actions:
            if item.target in {"living_room_light", "kitchen_light"}:
                working[item.target]["on"] = item.action == "turn_on"
            elif item.target == "living_room_thermostat":
                current = float(working[item.target]["temperature_c"])
                if item.action == "set_temperature":
                    new_temperature = float(item.value)
                elif item.action == "increase_temperature":
                    new_temperature = current + float(item.value)
                else:
                    new_temperature = current - float(item.value)
                if not 16 <= new_temperature <= 30:
                    raise ValueError("The resulting thermostat value must be between 16 and 30 C.")
                working[item.target]["temperature_c"] = int(new_temperature) if new_temperature.is_integer() else round(new_temperature, 1)
            elif item.target == "front_door_lock":
                working[item.target]["locked"] = item.action == "lock"
            elif item.target == "entertainment":
                if item.action == "play_media":
                    working[item.target]["status"] = "playing"
                    working[item.target]["title"] = (item.title or "Media").strip()
                elif item.action == "pause_media":
                    working[item.target]["status"] = "paused"
                else:
                    working[item.target] = {"status": "stopped", "title": ""}

        changes = []
        for target in working:
            if before[target] != working[target]:
                changes.append({
                    "target": target,
                    "before": before[target],
                    "after": working[target],
                    "summary": _describe_change(target, before[target], working[target]),
                })

        _DEVICES = working
        _REVISION += 1
        _UPDATED_AT = _now()
        execution_ms = round((time.perf_counter() - execution_started) * 1000, 2)
        total_ms = round((time.perf_counter() - request_started_at) * 1000, 2) if request_started_at else execution_ms
        event = {
            "timestamp": _UPDATED_AT,
            "event": "smart_home_command",
            "transcript": original_command,
            "goal": command.goal,
            "engine": engine,
            "validated_actions": [item.model_dump(exclude_none=True) for item in command.actions],
            "state_before": before,
            "state_after": copy.deepcopy(_DEVICES),
            "changes": copy.deepcopy(changes),
            "validation_success": True,
            "execution_verified": all(_DEVICES[item["target"]] == item["after"] for item in changes),
            "execution_ms": execution_ms,
            "total_ms": total_ms,
            "revision": _REVISION,
        }
        _EVENTS.appendleft(copy.deepcopy(event))
        snapshot = _snapshot_locked()

    _append_execution_log(event)
    change_text = "; ".join(change["summary"] for change in changes) or "The requested state was already set."
    return {
        "success": True,
        "message": change_text,
        "goal": command.goal,
        "actions": event["validated_actions"],
        "changes": changes,
        "verification": {"success": event["execution_verified"], "revision": event["revision"]},
        "state": snapshot,
        "timing": {"execution_ms": execution_ms, "total_ms": total_ms},
    }


def reset_smart_home(original_command: str = "Manual dashboard reset") -> dict:
    """Restore a predictable demo state and record the reset."""
    global _DEVICES, _REVISION, _UPDATED_AT
    with _LOCK:
        before = copy.deepcopy(_DEVICES)
        _DEVICES = copy.deepcopy(_INITIAL_DEVICES)
        _REVISION += 1
        _UPDATED_AT = _now()
        event = {
            "timestamp": _UPDATED_AT,
            "event": "smart_home_reset",
            "transcript": original_command,
            "engine": "deterministic",
            "state_before": before,
            "state_after": copy.deepcopy(_DEVICES),
            "validation_success": True,
            "execution_verified": _DEVICES == _INITIAL_DEVICES,
            "execution_ms": 0,
            "total_ms": 0,
            "revision": _REVISION,
        }
        _EVENTS.appendleft(copy.deepcopy(event))
        snapshot = _snapshot_locked()
    _append_execution_log(event)
    return {"success": True, "message": "Smart home reset to the demo state.", "state": snapshot}
